# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 08:29
from __future__ import unicode_literals

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('course_img', models.ImageField(storage=lib.storage.ImageStorage(), upload_to='course/img/%Y/%m/%d', verbose_name='\u8bfe\u7a0b\u4ecb\u7ecd\u56fe\u7247')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bb2\u5e08')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8def\u7ebf\u540d\u79f0')),
                ('path_img', models.ImageField(storage=lib.storage.ImageStorage(), upload_to='path/img/%Y/%m/%d', verbose_name='\u8def\u7ebf\u4ecb\u7ecd\u56fe\u9762')),
                ('desc', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='\u8def\u7ebf\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u8def\u7ebf',
                'verbose_name_plural': '\u8def\u7ebf',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6280\u672f\u7c7b\u522b')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='\u989c\u8272')),
                ('desc', models.TextField(default='', verbose_name='\u6280\u672f\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u5206\u7c7b',
                'verbose_name_plural': '\u6280\u672f\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tech',
            field=models.ManyToManyField(to='tracks_learning.Technology', verbose_name='\u6280\u672f\u5206\u7c7b'),
        ),
    ]
