# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import lib.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('position', models.CharField(max_length=256, verbose_name='\u804c\u4f4d')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='\u9762\u8bd5\u9898\u6570\u91cf')),
                ('lowest_monthly_salary', models.CharField(max_length=256, verbose_name='\u6700\u4f4e\u6708\u85aa')),
                ('highest_monthly_salary', models.CharField(max_length=256, verbose_name='\u6700\u9ad8\u6708\u85aa')),
                ('question_img', models.ImageField(storage=lib.storage.ImageStorage(), upload_to='interview_questions/img/%Y/%m/%d', verbose_name='\u9762\u8bd5\u9898\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u4f01\u4e1a\u9762\u8bd5\u9898',
                'verbose_name_plural': '\u4f01\u4e1a\u9762\u8bd5\u9898',
            },
        ),
    ]
