# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import lib.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u76f4\u64ad\u540d\u79f0')),
                ('pathwel', models.ImageField(storage=lib.storage.ImageStorage(), upload_to='live/img/%Y/%m/%d', verbose_name='\u76f4\u64ad\u56fe\u7247')),
                ('desc', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='\u76f4\u64ad\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u76f4\u64ad',
                'verbose_name_plural': '\u76f4\u64ad',
            },
        ),
    ]
